// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TvMazeScrapper.Data;

namespace TvMazeScrapper.Migrations
{
    [DbContext(typeof(ShowCastDbContext))]
    [Migration("20200111093310_FirstMigration")]
    partial class FirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113");

            modelBuilder.Entity("TvMazeScrapper.Models.CastModel", b =>
                {
                    b.Property<long>("CastId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Birthday");

                    b.Property<long>("Id");

                    b.Property<string>("Name");

                    b.Property<int>("ShowModelId");

                    b.Property<long?>("ShowModelShowId");

                    b.HasKey("CastId");

                    b.HasIndex("Birthday");

                    b.HasIndex("CastId")
                        .IsUnique();

                    b.HasIndex("ShowModelShowId");

                    b.ToTable("CastDb");
                });

            modelBuilder.Entity("TvMazeScrapper.Models.PageNumberModel", b =>
                {
                    b.Property<int>("PageNumberModelId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PageNumber");

                    b.HasKey("PageNumberModelId");

                    b.ToTable("PageNumberDb");
                });

            modelBuilder.Entity("TvMazeScrapper.Models.ShowModel", b =>
                {
                    b.Property<long>("ShowId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Id");

                    b.Property<string>("Name");

                    b.HasKey("ShowId");

                    b.HasIndex("Id");

                    b.HasIndex("ShowId")
                        .IsUnique();

                    b.ToTable("ShowDb");
                });

            modelBuilder.Entity("TvMazeScrapper.Models.CastModel", b =>
                {
                    b.HasOne("TvMazeScrapper.Models.ShowModel")
                        .WithMany("Cast")
                        .HasForeignKey("ShowModelShowId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
